### ISSUE TITLE
Learn tests don't seem to work for the "Calculator" requirement

### ISSUE THREAD

**Issue by rossmawd** [learn-co-curriculum/js-advanced-functions-basic-functions-review-lab#6] opened 2019-06-16 20:20 UTC
Even if you paste in the solution

**Comment by sgharms** [comment] 2019-06-18 20:53
@rossmawd I can't reproduce this. Using `index.js` in commit `0c86c7b77e9ff`, it works for me. Can you retry and / or provide screen shots?

**Comment by sgharms** [comment] 2019-06-19 11:38
@rossmawd I checked your fork and see you got the code working and seem to have the same 0c86c7b77e9ff available in your solution branch as we have in the repo master. I'm going to close this pending further update from you. Will re-open when / if you have a chance to update.

**Closed by sgharms** 2019-06-19 11:38 UTC
